# Usamos una versión ligera de Node.js sobre Alpine Linux
FROM node:20-alpine

# Instalamos dependencias necesarias para algunas librerías de Node si fuera necesario
RUN apk add --no-cache python3 g++ make

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero los archivos de dependencias para aprovechar la caché de capas de Docker
COPY package*.json ./

# Instalamos las dependencias (solo las de producción si quieres, pero para el TFG mejor todas)
RUN npm install

# Copiamos el resto del código fuente
COPY . .
